### PR TITLE
fix gc unsafe.

### PR DESCRIPTION
**Pull request by enthus1ast**

### CODE REVIEW

**Comment by niv** [comment]
Wouldn't this break? The global map is global because it is needed between readData calls.

What about making it thread-local instead (though that will potentially break too for multithreaded httpds that shard out request handlers)?

Maybe this needs a bigger API change and move responsibility for this elsewhere.

**Comment by enthus1ast** [comment]
Yep, we need to get rid of the global.

**Comment by dom96** [comment]
Nim needs a way for libraries to initialise thread-local vars.

CC @Araq

**Comment by Araq** [comment]
We had introduced a mechanism for that but it encouraged races everywhere so we removed it again.

**Comment by niv** [comment]
Well, re: the patch: We can make it a thread-local and init it on first usage, but then it'll break for dispatch-style servers (I don't think any of these exist). It would definitely have to be documented.

Moving it into the function scope seems wrong to me, as pings will never be answered (the table will always be empty for every new request unpack).

**Comment by dom96** [comment]
@Araq how did it encourage races? Maybe the mechanism's implementation was wrong? :P

**Comment by enthus1ast** [comment]
@niv mabye something like a `websocketContext` ?

**Comment by Araq** [comment]
Why not use a SharedTable instead? Needs ``protect`` and ``dispose`` for the Future but it's possible.

**Pull request closed without merging**
