### PR TITLE
Allow custom SSL context for client

### PR DESCRIPTION
**Pull request by hlaaftana**

### CODE REVIEW

**Comment by niv** [comment]
Tyvm. :)

**Comment by niv** [comment]
So, I've merged this, but it appears to think that `newContext` doesn't exist, despite `net` being imported. Any idea why this would be?

**Comment by hlaaftana** [comment]
Maybe we should try specifying `net.newContext` or giving it `protVersion = protTLSv1`? Or if this is being tested in a different module nim might be directly doing `newContext` in the test module even though net isn't imported in the test module.

**Comment by erhlee-bird** [comment]
Looking at net.nim, newContext is defined only when ssl is defined.

**Comment by hlaaftana** [comment]
Very correct, fixed in #25

**Pull request merged**
